--zeus.register_item("materials:stick", {
--    name = "Stick",
--    groups = {
--        stick = 1,
--    },
--    textures = {
--        "zeus:materials:stick_0",
--        "zeus:materials:stick_1",
--        "zeus:materials:stick_2",
--        "zeus:materials:stick_3"
--    }
--})