runfile(_PATH .. "block")
runfile(_PATH .. "block_foliage")
runfile(_PATH .. "crosslarge")
runfile(_PATH .. "halfslab")
runfile(_PATH .. "halfslab_foliage")
runfile(_PATH .. "leaflike")
runfile(_PATH .. "plantlike")